### ISSUE TITLE
RequireJS bundeling: TypeError: Promise is not function 

### ISSUE THREAD

**Issue by mlandry360** [opbeat/opbeat-js#21]
Hi,

I'm trying to install opbeat in my angular app and I'm getting that error: 
TypeError: Promise is not a function

It looks like it crash in  /instrumentation/trace.js at line 19 when it try to create a new instance of Promise.

I have these dependencies injected in my app : 
        'ui.bootstrap',
        'ngRoute',
        'ngCookies',
        'ngMessages',
        'pascalprecht.translate',
        'ngFileUpload',
        'toggle-switch',
        'angular-sortable-view',
        'ngOpbeat'

I set debug to true and I have this logged lines: 

opbeat.install.already.installed
angular-opbeat.js?v=v1:3739 opbeat.instrumentation.TransactionStore.getRecentByUrl http://localhost:8080/#/ undefined
angular-opbeat.js?v=v1:3739 opbeat.instrumentation.TraceBuffer.startTrace $templatesCache PUT template/accordion/accordion-group.html

And the stacktrace of the error: 
TypeError: Promise is not a function
    at new module.exports (https://d3tvtfb6518e3e.cloudfront.net/1/angular-opbeat.js?v=v1:2730:20)
    at TraceBuffer.startTrace (https://d3tvtfb6518e3e.cloudfront.net/1/angular-opbeat.js?v=v1:2853:15)
    at Object.instrumentMethodBefore (https://d3tvtfb6518e3e.cloudfront.net/1/angular-opbeat.js?v=v1:3425:29)
    at Object.opbeatFunctionWrapper [as put] (eval at _buildWrapperFunction (https://d3tvtfb6518e3e.cloudfront.net/1/angular-opbeat.js?v=v1:3496:11), <anonymous>:13:32)
    at http://localhost:8080/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js?v=v1:10:6491
    at Object.e [as invoke] (http://localhost:8080/vendor/angular/angular.min.js?v=v1:39:394)
    at http://localhost:8080/vendor/angular/angular.min.js?v=v1:41:271
    at n (http://localhost:8080/vendor/angular/angular.min.js?v=v1:7:333)
    at eb (http://localhost:8080/vendor/angular/angular.min.js?v=v1:41:247)
    at c (http://localhost:8080/vendor/angular/angular.min.js?v=v1:19:463)

I installed es6-promise via npm because it looks like it's required in trace.js but it still crash.Does anybody got this problem?

Angular Version : 1.4.8

Thanks,
Max

**Comment by auchenberg** [comment]
Which browser are you using? We use the ES6-Promise polyfil, so Promises should be around regardlessly.

**Comment by mlandry360** [comment]
I'm on Chrome 47.0.2526.106 m. I tested Firefox 42 too and I got the same problem.

**Comment by auchenberg** [comment]
Hi @mlandry360 

We just released version 1.2.2 to our CDN, which disables `$httpBackend` instrumentation, as it causes issues in Angular 1.4.8.

Can I get you to try again? I'm unable to reproduce this issue using Angular 1.4.8.

**Comment by mlandry360** [comment]
Hi, 
I justed tested it and I'm getting the same error: 

opbeat version: v1.2.2
angular-opbeat.js?v=1450886088175:3725 opbeat.instrumentation.TransactionStore.getRecentByUrl http://localhost:8080/#/ undefined
angular-opbeat.js?v=1450886088175:3725 opbeat.instrumentation.TraceBuffer.startTrace $templatesCache PUT template/accordion/accordion-group.html
require.js:900 TypeError: Promise is not a function(…)Module.check @ require.js:900(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56Module.emit @ require.js:1189Module.check @ require.js:940Module.enable @ require.js:1177Module.init @ require.js:783callGetModule @ require.js:1204context.completeLoad @ require.js:1604context.onScriptLoad @ require.js:1711
47angular-opbeat.js?v=1450886088175:3725 Instrumentation.scheduler._dispatch 0

I did a console.log of the version for being sure I was loading the 1.2.2.

**Comment by auchenberg** [comment]
@mlandry360 Ah. Are you loading angular-opbeat via `RequireJS`? What does your RequireJS config look like?

**Comment by mlandry360** [comment]
Yes I'm loading it with RequireJS. I'm loading opbeat after angular and my app.js (who is responsable to inject ngOpbeat and configure it)

```javascript

require.config ({
    baseUrl: './',
    paths: {
        angular: 'vendor/angular/angular.min',

        // Angular modules
        angularRoute: 'vendor/angular-route/angular-route.min',
        angularCookies: 'vendor/angular-cookies/angular-cookies.min',
        angularMessages: 'vendor/angular-messages/angular-messages.min',
        angularBootstrap: 'vendor/angular-bootstrap/ui-bootstrap-tpls.min',
        angularTranslate: 'vendor/angular-translate/angular-translate.min',
        angularTranslateStorageCookie: 'vendor/angular-translate-storage-cookie/angular-translate-storage-cookie.min',
        angularTranslateLoader: 'vendor/angular-translate-loader-static-files/angular-translate-loader-static-files.min',
        angularBootstrapSwitch: 'vendor/angular-bootstrap-toggle-switch/angular-toggle-switch.min',
        ngFileUpload: 'vendor/ng-file-upload/ng-file-upload-all.min',
        angularSortableView: 'vendor/angular-sortable-view/src/angular-sortable-view.min',

        // Libs
        jquery: 'vendor/jquery/dist/jquery.min',
        bootstrap: 'vendor/bootstrap-sass/assets/javascripts/bootstrap.min',
        moment: 'vendor/moment/min/moment.min',
        rxjs: 'vendor/rxjs/dist/rx.all.min',
        sockjs: 'vendor/sockjs/sockjs',
        vertxbus: 'vendor/vertx3-eventbus-client/vertxbus',
        opbeat: 'https://d3tvtfb6518e3e.cloudfront.net/1/angular-opbeat',

        // Models
        Entity: 'dist/js/models/Entity.min',
        User: 'dist/js/models/User.min',
        Theme: 'dist/js/models/Theme.min',
        BaseConfig: 'dist/js/models/BaseConfig.min',
        ThemeConfig: 'dist/js/models/ThemeConfig.min',
        FieldType: 'dist/js/models/FieldType.min',
        Field: 'dist/js/models/Field.min',
        ProductFamily: 'dist/js/models/ProductFamily.min',
        Recipient: 'dist/js/models/Recipient.min',
        Subscription: 'dist/js/models/Subscription.min',
        ContactConfig: 'dist/js/models/ContactConfig.min',
        EmailConfig: 'dist/js/models/EmailConfig.min',
        Site: 'dist/js/models/Site.min',

        // App
        app: 'dist/js/app.min',
        directives: 'dist/js/directives.min',
        controllers: 'dist/js/controllers.min',
        services: 'dist/js/services.min'
    },
    shim: {
        angular: { deps: ['jquery'] },

        // Angular modules need angular to be loaded first
        angularRoute: ['angular'],
        angularCookies: ['angular'],
        angularMessages: ['angular'],
        angularBootstrap: ['angular'],
        angularTranslate: ['angular'],
        angularSortableView: ['angular'],
        angularTranslateStorageCookie: ['angular', 'angularTranslate'],
        angularTranslateLoader: ['angular', 'angularTranslate'],
        angularBootstrapSwitch: ['angular', 'bootstrap'],
        ngFileUpload: ['angular'],

        // Depend on jQuery
        bootstrap: { deps: ['jquery'] },

        // Angular core files need app and angular loaded for working
        services: { deps: ['app', 'angular'] },
        controllers: { deps: ['app', 'angular'] },
        directives: { deps: ['app', 'angular'] },
        opbeat: { deps: ['app', 'angular'] },

        // Dependencies injected in AngularJS main module need to be loaded first
        app: {
            deps: [
                'jquery',
                'angularRoute',
                'angularCookies',
                'angularMessages',
                'angularBootstrap',
                'angularTranslate',
                'angularTranslateStorageCookie',
                'angularTranslateLoader',
                'ngFileUpload',
                'angularBootstrapSwitch',
                'angularSortableView'
            ]
        },
    },

    priority: ['angular'],
    //urlArgs: "v=" + new Date().getTime()   //  *** Cache bust for DEV ONLY ***
});

// Load js files and bootstrap angular app
require([
    'opbeat',
    'rxjs',
    'bootstrap',
    'angular',
    'vertxbus',

    'app',
    'services',
    'controllers',
    'directives'
], function () {
    angular.element(document).ready(function () {
        angular.bootstrap(document, ['app']);
    });
});


```

In my app.js I setup it like this:

```javascript

    app.config(function ($opbeatProvider) {
            console.log("opbeat version: "+ $opbeatProvider.version)
            $opbeatProvider.config({
                angularAppName: 'app',
                debug: true,
                orgId: '<my_org_id>',
                appId: '<my_app_id>'
            })
        });

```

**Comment by mlandry360** [comment]
Ok it looks it related to that new issue : https://github.com/opbeat/opbeat-js/issues/28

If I set my config with performance.enable: false, my app boot with no more error.

'''javascript
    app.config(function ($opbeatProvider) {
            console.log("opbeat version: "+ $opbeatProvider.version)
            $opbeatProvider.config({
                angularAppName: 'app',
                performance: {
                    enable: false
                },
                debug: true,
                orgId: '6972740a4ef64bda9b07b9a3423c9bb6',
                appId: 'f1c709530c'
            })
        });
'''

**Comment by jahtalab** [comment]
[version 1.2.9](https://github.com/opbeat/opbeat-js/tree/v1.2.9) fixes this.
