### ISSUE TITLE
CDN version of angular-opbeat doesn't include any version information

### ISSUE THREAD

**Issue by piotrowski** [opbeat/opbeat-js#35]
It would be great if https://d3tvtfb6518e3e.cloudfront.net/1/angular-opbeat.min.js and https://d3tvtfb6518e3e.cloudfront.net/1/angular-opbeat.js would include information about the deployed version of the library. 

That way, uses that have to work with local copies (e.g. Ionic mobile apps that have to work with no network), would easier be able to distinguish different versions.

**Comment by mlandry360** [comment]
You have access to version number using the $opbeatProvider once ngOpbeat is injected in your app.

console.log("opbeat version: "+ $opbeatProvider.version)

**Comment by piotrowski** [comment]
Ah nice, thanks. Didn't know and didn't see anything on a quick look at the code.

Searching for "VERSION" or "this.version" in the code also gets you the version number.
