### ISSUE TITLE
opbeat-angular performance tracking injects number instead of a service when JS is minified (parameter named "i")

### ISSUE THREAD

**Issue by johny-gog** [opbeat/opbeat-js#38]
After using uglifyJS (or using other js compressor) we got a lot of errors, it turned out there are **numbers injected instead of services**.

This is a serious issue and for now it prevents us from using opbeat in our company at all.
I've played with it for a while and it turned out that just changing names in constructor function will cause the bug.
(edit)
Interestingly, not in all cases, only one service gets injected as a number - **one that is named `i`**.

So, simply if I use `i` as a parameter name, it gets some iterator value instead of service.
**Here is a very simple example that shows it all:**
**https://jsfiddle.net/heLvms8s/5/**

I wonder if there is more - other variable names that would cause this.

---

Here is the base code that I started with:
https://jsfiddle.net/8zzjdcak/8/

Here is slightly modified code that have just parameters minified, and it doesn't work:
https://jsfiddle.net/4hncccdw/3/

**Comment by jahtalab** [comment]
Hi @johny-gog ,

This is fixed with [version 1.2.8 release](e2deb270d198a38dc9cb034c53b76b45b69aa618)
Let me know how it works out.

Thanks for reporting the issue,
Hamid

**Comment by johny-gog** [comment]
Thank you @jahtalab. :) Could you please describe or add link to commit - what was the fix?

**Comment by jahtalab** [comment]
@johny-gog , the problem was with trying to patch functions while keeping the arguments name for dependency injection, but the better way is to use $inject internally while using arguments name.

[this is the commit](80e2d2911b60bf5bed9a077c55d2e2af919cc8c8)

**Comment by johny-gog** [comment]
The commit link is broken again. :)

**Comment by jahtalab** [comment]
@johny-gog, sorry about, it's fixed now.

**Comment by johny-gog** [comment]
Great. :) Thank you again - now we can try to use opbeat on production. :+1:
