### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'window.angular.module')

### ISSUE THREAD

**Issue by rwillmer** [opbeat/opbeat-js#43]
I'm trying to get opbeat working in my AngularJS app.

I've followed the instructions but it fails with this error when loading the opbeat script.

>   TypeError: undefined is not an object (evaluating 'window.angular.module')
>   (anonymous function) angular-opbeat.js:1828
>   s angular-opbeat.js:16
>   e angular-opbeat.js:25
>   (anonymous function)angular-opbeat.js:27

This was using the non-minified version, but it's the same error on the npm-installed version, and the CDN.

I'm using AngularJS 1.4.9.

**Comment by jahtalab** [comment]
Hi @rwillmer,

You need to make sure that angular.js is loaded before angular-opbeat.js.
Are you using a module loader?

Cheers,
Hamid

**Comment by rwillmer** [comment]
Ah, that was indeed the problem. Thanks
