### ISSUE TITLE
cannot be invoked in strict mode

### ISSUE THREAD

**Issue by rwillmer** [opbeat/opbeat-js#44]
I have ng-strict-di turned on, opbeat-js gives me this

angular.js:4574Error: [$injector:modulerr] Failed to instantiate module app due to:
[$injector:strictdi] function($opbeatProvider) is not using explicit annotation and cannot be invoked in strict mode

Angular 1.4.9

**Comment by rwillmer** [comment]
If I remove the ng-strict-di, then I don't get an error, but my website just displays blank.

**Comment by jahtalab** [comment]
For strict di to work, you need to annotate dependencies with an array or with $inject:

    angular.module('app', ['ngOpbeat'])
    .config(['$opbeatProvider', function ($opbeatProvider) {
        $opbeatProvider.config({
        debug: true, // Enables debug-mode which outputs logging to the console
        orgId: '<org id>',
        appId: '<app id>'
        })

        $opbeatProvider.install()
    }])

You can find more info about strict di [here](https://docs.angularjs.org/error/$injector/strictdi)
Let me know if that solves the problem.

**Comment by rwillmer** [comment]
Of course! <doh> Might be worth adding that into the documentation?

Thanks

**Comment by rwillmer** [comment]
P.S. All working now and I've just seen my first error on opbeat. <happy>

**Comment by jahtalab** [comment]
We'll sort out documentation soon.
Glad to hear it's working :+1:
