### ISSUE TITLE
Fix npm package name?

### ISSUE THREAD

**Issue by jordansexton** [opbeat/opbeat-js#5]
`npm info opbeat-js`
```javascript
{ name: 'opbeat-js',
  description: 'An experimental JS client for logging exceptions and stacktraces to Opbeat',
  'dist-tags': { latest: '0.0.2' },
  versions: [ '0.0.1', '0.0.2' ],
  maintainers: [ 'vanjacosic <vanja@cosic.dk>' ],
  time:
   { modified: '2015-08-04T10:11:15.989Z',
     created: '2015-07-14T17:15:56.179Z',
     '0.0.1': '2015-07-14T17:15:56.179Z',
     '0.0.2': '2015-08-04T10:11:15.989Z' },
  homepage: 'https://github.com/vanjacosic/opbeat-js',
  repository:
   { type: 'git',
     url: 'https://vanjacosic@github.com/vanjacosic/opbeat-js.git' },
  author: 'Vanja Cosic, Matt Robenolt and other contributors',
  bugs: { url: 'https://github.com/vanjacosic/opbeat-js/issues' },
  license: 'BSD-2-Clause',
  readmeFilename: 'README.md',
  version: '0.0.2',
  main: 'dist/opbeat.js',
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  dependencies: {},
  devDependencies:
   { gulp: '^3.8.9',
     'gulp-concat': '^2.4.1',
     'gulp-livereload': '^2.1.1',
     'gulp-serve': '^0.2.0',
     'gulp-uglify': '^1.0.1' },
  gitHead: '250aea951c025f539d7bf3733bdacd78eb3bfdd9',
  dist:
   { shasum: '85cc6fcce6c0b7c07d78ee3f4186462a5ee14a2a',
     tarball: 'http://registry.npmjs.org/opbeat-js/-/opbeat-js-0.0.2.tgz' },
  directories: {} }
```

[vanjacosic/opbeat-js](https://github.com/vanjacosic/opbeat-js) is deprecated, but the official project's [package.json](https://github.com/opbeat/opbeat-js/blob/a8672b002d9f6c24d726de2e8c95251c9028f2ad/package.json) has `opbeat-js` as the name. I'm currently working around this by installing from Github, but would @vanjacosic be willing to relinquish the npm name?

**Comment by auchenberg** [comment]
Hi @jordansexton 

We just opened sourced `opbeat-js`, and in the BETA phase we don't plan on releasing the module to NPM, as we iterate rather fast. Once we have a stable version in place, we'll push it to NPM.

Let me know if you have any issues.

/k

**Comment by jordansexton** [comment]
Makes sense. I knew the Node lib was beta, but I didn't know the client lib is. Thanks!

**Comment by auchenberg** [comment]
We just released our JavaScript and AngularJS modules last week: https://opbeat.com/blog/posts/opbeat-for-angularjs/

**Comment by vanjacosic** [comment]
@jordansexton 
Just for the record: I will relinquish the name once the module is ready for publishing on npm. I work at Opbeat as well, so we will just coordinate that internally. But thanks for bringing it up! 👌

**Comment by jordansexton** [comment]
Got it. You guys are doing great work!
