### ISSUE TITLE
Deprecated dequeueTask and enqueueTask (v2.0)

### ISSUE THREAD

**Issue by juliusosokinas** [opbeat/opbeat-js#50]
Console outputs:

`'DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask'`

`DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask`

**Comment by jahtalab** [comment]
Version 2.0.2 fixes the issue.

**Comment by juliusosokinas** [comment]
For some reason I still see "dequeueTask" warning when in [PhantomJS](https://travis-ci.org/ExCiteS/airquality/jobs/121438209) and [Chrome](https://travis-ci.org/ExCiteS/airquality/jobs/121438210) but not [Firefox](https://travis-ci.org/ExCiteS/airquality/jobs/121438211) (before it was in Firefox too).

**Comment by jahtalab** [comment]
Thanks for the quick feedback, I will get back to you soon.
