### ISSUE TITLE
Sending transactions when Opbeat not installed (Angular version v2.0)

### ISSUE THREAD

**Issue by juliusosokinas** [opbeat/opbeat-js#51]
On my app I use `$opbeatProvider.install()`only when "orgId" and "appId" is set on app configuration. However, I noticed that even without `install()` transactions are being sent:

```
POST https://intake.opbeat.com/api/v1/organizations/null/apps/null/client-side/transactions/ 401 (Unauthorized)
```

**Comment by jahtalab** [comment]
Version 2.0.2 fixes the issue.

**Comment by juliusosokinas** [comment]
Thanks.

I'm just not very keen on having logs like "Config is not valid"... Let's image situation, where configuration is there but for one or another reason you just don't want Opbeat to be active...

**Comment by jahtalab** [comment]
You make a valid point. 
Although, as a feature request, do you prefer for Opbeat to be completely deactivated or just not send any data to the server?
Could you elaborate on your use case?

I appreciate your feedback

**Comment by juliusosokinas** [comment]
Ideally, I would like to see the possibility to completely switch Opbeat on and off, instead of having just `install()`.

In my case, app has a configuration where Opbeat settings can be added or not. If they are added, Opbeat then is initialised. But because it's a hybrid mobile app with a possibility to work in offline mode, I would like to switch Opbeat off when a device is offline (there's no point of sending requests, they not gonna reach your servers) and back on when a device becomes online again.

Yet another possibility would be, as you said, to only switch off data sending to the server. Yes, it would be valid too for my case scenario.

To add to this, I'd say a setting to completely switch off all console logging would be great. Also, if let's say there's a new feature to switch off data sending to the server, yet another cool feature would be to cache those requests to push manually (in my case, when becoming online).

Thanks!

**Comment by jahtalab** [comment]
Thanks for your thorough response , I created two issues as enhancements.
Don't hesitate to contact me if you want to add something.

Cheers

**Comment by evertongx** [comment]
Having this issue on version 3.0.1, i am not calling `install()` and `config()` and the transections are being sent.

**Comment by jahtalab** [comment]
Hi @evertongx ,

Thanks for reporting the issue.

Have you set `app-id` and `org-id` attributes on the script tag that loads Opbeat? (That's another way of configuration)

**Comment by evertongx** [comment]
@jahtalab being set inside of a `if()` that the condition is true just when is on production server.

**Comment by juliusosokinas** [comment]
@evertongx, remove `install()`, and put `config()` inside the `if()`. As I found out, the installation is automatic by default now.

**Comment by evertongx** [comment]
@juliusosokinas that's the problem, it is already inside of the `if`.

**Comment by jahtalab** [comment]
Hi @evertongx , 

I've sent you an email two days ago, Have you received it?
I think it would be faster and more convenient if we continue via email or in-app chat.
You can find more info about our support [here](https://opbeat.com/docs/support/).

Thanks,
Hamid
