### ISSUE TITLE
Why is angular-opbeat so big?

### ISSUE THREAD

**Issue by Zertz** [opbeat/opbeat-js#55]
| angular-opbeat.min.js | opbeat.min.js |
| --- | --- |
| 72 KB | 30 KB |

Any chance for some weight to be shaved off the angular build?

**Comment by jahtalab** [comment]
Thanks for reaching out. 
angular-opbeat supports performance monitoring for AngularJS that's why it is bigger.
But we're working to make it as small as possible.

Cheers

**Comment by Zertz** [comment]
The monitoring does look awesome! I'm just wondering what's making the bundle so large, the angular stuff in `src/angular/` is small enough that it has to be a bundled dependency adding weight to the library?

**Comment by jahtalab** [comment]
`src/angular` Only contains angular-specific instrumentations. But other parts of the library are also necessary for performance monitoring which are not in that folder.
Your also right about dependencies, notably: zone.js
