### ISSUE TITLE
"Cannot call method 'now' of undefined" 

### ISSUE THREAD

**Issue by giorgosp** [opbeat/opbeat-js#57]
Hello, Im seeing a lot of errors "Cannot call method 'now' of undefined".

The user agent string is 
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Web Preview) 
> Chrome/27.0.1453 Safari/537.36

and the stacktrace:
 
> new r@https://d3tvtfb6518e3e.cloudfront.net/2/angular-opbeat.min.js 3:1396  
> 
>     , e, n, r) {
>       this.transaction = t, this.signature = e, this.type = n, this.ended = !1, this._parent = null, this._diff = null, this._end = null, this._start = window.performance.now(), this._startStamp = new Date, this._isFinish = new o(function(t, e) {
>         this._markFinishedFunc = t
>       }.bind(this)), (s.isUndefined(r) || null == r) && (r = {});
>       var i = r.e
> 

I understand that most browsers support the window.performance api but is there a chance that you will support older browsers?

**Comment by jahtalab** [comment]
Hi,
Thanks for reporting the issue. Supporting older browsers is on our plan. I will update this issue as we progress.
