### ISSUE TITLE
Release on NPM

### ISSUE THREAD

**Issue by auchenberg** [opbeat/opbeat-js#6]

**Comment by mfc-julius** [comment]
Waiting for this :+1:

**Comment by piotrowski** [comment]
+1

**Comment by mgerstenblatt** [comment]
+1

**Comment by vanjacosic** [comment]
Sorry for the wait everyone. @jahtalab and I have just published the latest version to npm and updated the README quickly.

Let us know if it works for you!

**Comment by mfc-julius** [comment]
Thanks @vanjacosic, it works! Although, not sure why there would be a version folder included inside "dist".

What about Bower release?

**Comment by jahtalab** [comment]
@juliusosokinas, this is a beta release, the folder structure might change a little bit in the coming releases.

A bower release is not on our plan right now, maybe in the future.
