### ISSUE TITLE
Unknown opbeat-angular problem with "readystatechange" on PhantomJS

### ISSUE THREAD

**Issue by juliusosokinas** [opbeat/opbeat-js#66]
I cannot track down the problem just yet, but recent versions keep throwing me the error, when running a PhantomJS script on Node.js (retrieving and opening page, where Opbeat is added as a vendor): `TypeError: undefined is not an object (evaluating 'opbeatData.registeredEventListeners['readystatechange'].resolved')`.

Everything was fine with version 3.0.1 and lower, though from 3.1.0 and up this is happening.

**Comment by jahtalab** [comment]
Hi @juliusosokinas ,

Thanks for reporting the issue.
Which version of PhantomJS do you use?

**Comment by juliusosokinas** [comment]
PhantomJS itself is version 2.1.1, npm wrapper is version 2.1.7.

**Comment by jahtalab** [comment]
Hi @juliusosokinas ,

I've just released opbeat-angular version 3.1.3, that will fix this issue.
Could I get you to try again?

Cheers,
Hamid

**Comment by juliusosokinas** [comment]
I can confirm that the issue has been fixed. Thanks for being so quick! Great job.

**Comment by jahtalab** [comment]
Awesome.
Thanks and have a good one :)
