### ISSUE TITLE
3.2.0 breaks unit tests (Karma)

### ISSUE THREAD

**Issue by juliusosokinas** [opbeat/opbeat-js#69]
The latest release breaks all the tests (Travis CI - https://travis-ci.org/ExCiteS/airquality/builds/155287193).

Were there some major changes?

**Comment by jahtalab** [comment]
Hi @juliusosokinas ,

Thanks for reporting the issue.
It seems to be a bug on our side and I'm currently working on a patch. I will update this issue when the fix is available.

Have a good one,
Hamid

**Comment by jahtalab** [comment]
@juliusosokinas ,

I've release opbeat-angular v3.2.1 which should fix this issue.
Could I get you to try again?

**Comment by juliusosokinas** [comment]
I can confirm that the issue has been resolved. Thanks!
