### ISSUE TITLE
Missing stacktrace frame keys (400 response)

### ISSUE THREAD

**Issue by bjudson** [opbeat/opbeat-js#70]
Got this response from OpBeat:
```
{
    "status": 400, 
    "error_message": "Unable to validate data.", 
    "structured_error": {
        "stacktrace": {
            "frames": {
                "3": {
                    "lineno": "Missing required key", 
                    "filename": "Missing required key"
                }
            }
        }
    }
}
```

Using Chrome 52. When I look at the payload, `stacktrace.frames[3]` is an empty object (`{}`). Not sure if this is a Chrome bug, an issue with source maps or something else outside of OpBeat's control. But it would be nice if OpBeat was able to throw out invalid frames rather than rejecting the entire report.

**Comment by jahtalab** [comment]
@bjudson ,

Thanks for reporting the issue and sorry for the slow response. 
Which version of opbeat are currently using?

**Comment by bjudson** [comment]
@jahtalab Looks like we're using 1.2.11 (https://d3tvtfb6518e3e.cloudfront.net/1/opbeat.min.js)

**Comment by jahtalab** [comment]
@bjudson ,

It should be fixed in the latest version (https://d3tvtfb6518e3e.cloudfront.net/3/opbeat.min.js)
I will close this one but feel free to reopen if the issue still exists.

Cheers
